services:
  postgres:
    restart: unless-stopped

  backend:
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  nginx:
    build:
      context: ./infra/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot_webroot:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - mathingo_net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    networks:
      - mathingo_net

volumes:
  certbot_webroot:
